plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.permissions'
version = '1.0.0'

android {
  namespace 'expo.modules.permissions'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'androidx.core:core:1.10.1'
  implementation 'androidx.appcompat:appcompat:1.6.1'
}
